[package]
name = "reversi-wasm-core"
version = "0.1.1"
authors = ["Kazushi Kitaya <kazushikitaya@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde_json = "1.0"
rand = "0.6"
